- hosts: all 
  sudo: yes
  sudo_user: root
  gather_facts: true
  tasks:
      - name: Create file
        file:
            path: /tmp/yallo
            state: touch
      - name: Update Hosts File
        blockinfile:
          path: /etc/hosts
          block:  |
            172.17.8.101 node1
            172.17.8.102 node2
            172.17.8.103 node3
            172.16.8.104 node4
      # Does Not Work
      - name: Replace DNS
        lineinfile:
          path: /etc/resolv.conf
          line: 'nameserer 8.8.8.8'
      - name: Disable SE linux
        shell:  |
          setenforce 0
          sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
          exit 0
        args:
          executable: /bin/bash
      - name: Enable Netfilter
        shell:  |
          modprobe br_netfilter
          echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
          exit 0
        args:
          executable: /bin/bash
      - name: Remove Fstab from swap
        replace:
          path: /etc/fstab
          regexp: '/dev/mapper/VolGroup00-LogVol01 swap'
          replace: '#/dev/mapper/VolGroup00-LogVol01 swap'
      - name: Install Docker Deps
        yum:
          name: "{{ packages }}"
        vars:  
          packages:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2
      - name: Install Docker Repo
        shell: |
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          exit 0
        args:
          executable: /bin/bash
      - name: Install Docker CE
        yum:
          name: docker-ce
          state: latest
      - name: Enable Kubernetes yum repository
        yum_repository:
          name: kubernetes
          description: Kubernetes
          baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled: yes
          gpgcheck: yes
          repo_gpgcheck: yes
          gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg\nhttps://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
          state: present
      - name: Install Kubernets Components
        yum:
          name: "{{ packages }}"
        vars:  
          packages:
            - kubelet
            - kubeadm
            - kubectl
        register: task_result
      - name: Reboot System
        shell: "sleep 5 && reboot"
        async: 1
        poll: 0
        when: task_result is changed
      - name: Return Async Login After Reboot
        wait_for_connection:
          connection_timeout: 20
          sleep: 5
          delay: 5
          timeout: 300
        when: task_result is changed
      - name: Restart Docker and Kubelet
        shell:  |
          systemctl start docker && systemctl enable docker
          systemctl start kubelet && systemctl enable kubelet 
          exit 0
        args:
          executable: /bin/bash
      - name: change Kberetes cgroup-driver to 'cgroupfs'
        warn: false
        shell:  |
          sed -i 's/cgroup-driver=systemd/cgroup-driver=cgroupfs/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        args:
          executable: /bin/bash
      - name: Reload systemd
        shell:  |
          systemctl daemon-reload
        args:
          executable: /bin/bash

